=== jdm7dv/XSL/XMLforASPNETDevelopersCode/TestBed/ASP.NET Tricks/golfers.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.golfExample.com" xmlns="http://www.golfExample.com">
	<xsd:complexType name="courseType">
		<xsd:attribute name="city" type="xsd:string" use="required" />
		<xsd:attribute name="state" type="xsd:string" use="required" />
		<xsd:attribute name="name" type="xsd:string" use="required" />
	</xsd:complexType>
	<xsd:complexType name="favoriteCoursesType">
		<xsd:sequence>
			<xsd:element name="course" type="courseType" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="golferType">
		<xsd:sequence>
			<xsd:element name="name" type="nameType" />
			<xsd:element name="favoriteCourses" type="favoriteCoursesType" />
		</xsd:sequence>
		<xsd:attribute name="skill" type="xsd:string" use="required" />
		<xsd:attribute name="handicap" type="xsd:int" use="required" />
		<xsd:attribute name="clubs" type="xsd:string" use="required" />
		<xsd:attribute name="id" type="xsd:int" use="required" />
	</xsd:complexType>
	<xsd:element name="golfers">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="golfer" type="golferType" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="nameType">
		<xsd:sequence>
			<xsd:element name="firstName" type="xsd:string" />
			<xsd:element name="lastName" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== jdm7dv/XSL/XMLforASPNETDevelopersCode/TestBed/Chapter5/golfersNotValid(XSD).xml
<?xml version="1.0" encoding="UTF-8" ?>
<golfers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.golfExample.com" xsi:schemaLocation="http://www.golfExample.com golfers.xsd">
	<golfer1 skill="excellent" handicap="12" clubs="Taylor Made" id="1111">
		<name>
			<firstName>Paul</firstName>
			<lastName>Allsing</lastName>
		</name>
		<favoriteCourses>
			<course city="Pinetop" state="AZ" name="Pinetop Lakes CC" />
			<course city="Phoenix" state="AZ" name="Ocotillo" />
			<course city="Snowflake" state="AZ" name="Silver Creek" />
		</favoriteCourses>
	</golfer1>
	<golfer skill="moderate" handicap="8" clubs="Taylor Made" id="2222">
		<name>
			<firstName>Dan</firstName>
			<lastName>Wahlin</lastName>
		</name>
		<favoriteCourses>
			<course city="Pinetop" state="AZ" name="Pinetop Lakes CC" />
			<course city="Pinetop" state="AZ" name="White Mountain CC" />
			<course city="Springville" state="UT" name="Hobble Creek" />
		</favoriteCourses>
	</golfer>
</golfers>
